services:
  cups:
    container_name: cups
    image: gardner/cups-avahi-airprint
    restart: unless-stopped
    network_mode: "host"
    environment:
      CUPSADMIN: cups
      CUPSPASSWORD: cups
    volumes:
      - "./services:/services"
      - "./config:/config"
